//
//  SearchModels.swift
//  SpotifySearch
//
//  Created by Arash Goodarzi on 10/29/19.
//  Copyright (c) 2019 Arash Goodarzi. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Search {
    
    struct Request {
        
    }
    
    struct Response {
        let state: Result<Any, Error>
    }
    
    enum ViewModel {
        
        
        struct Success {
            
        }
        
        struct Loading {
            
        }
        
        struct Failure {
            var message: String? = nil
        }
        
    }
}
