//
//  SearchPresenter.swift
//  SpotifySearch
//
//  Created by Arash Goodarzi on 10/29/19.
//  Copyright (c) 2019 Arash Goodarzi. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchPresentationLogic: AnyObject {
    func presentSearchTracks(response: Search.Tracks.Response)
}

class SearchPresenter: SearchPresentationLogic {
    
    weak var viewController: SearchDisplayLogic?
    
    func presentSearchTracks(response: Search.Tracks.Response) {
        
        switch response.state {
        case .success(let tracks):
            
            let viewModel = Search.Tracks.ViewModel.Success(tracks: tracks)
            viewController?.displaySuccessSearchTracks(viewModel: viewModel)
            
        case .failure(let error):
            
            //server error
            if let serverError = error as? ServerModels.ServerErrorModel {
                let viewModel = Search.Tracks.ViewModel.Failure(message: serverError.error.message)
                viewController?.displayServerErrorSearchTracks(viewModel: viewModel)
                return
            }
            
            //error
            let viewModel = Search.Tracks.ViewModel.Failure(message: error.localizedDescription)
            viewController?.displayNoConnectionSearchTracks(viewModel: viewModel)
        }
    }
    //end of class
}
