//
//  SearchRouter.swift
//  SpotifySearch
//
//  Created by Arash Goodarzi on 10/29/19.
//  Copyright (c) 2019 Arash Goodarzi. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol SearchRoutingLogic: AnyObject {
    func routeToTrack()
}

protocol SearchDataPassing {
    var dataStore: SearchDataStore? { get }
}

class SearchRouter: NSObject, SearchRoutingLogic, SearchDataPassing {
    
    weak var viewController: SearchViewController?
    var dataStore: SearchDataStore?
    
    func routeToTrack() {
        let destinationVC = TrackViewController.instantiateFrom(storyboard: .main)
        guard var destinationDS = destinationVC.router?.dataStore, let dataStore = self.dataStore, let navController = viewController?.navigationController else {
            return
        }
        
        passDataToBizInfo(source: dataStore, destination: &destinationDS)
        navigateToBizInfo(source: navController, destination: destinationVC)
    }
    
    func passDataToBizInfo(source: SearchDataStore, destination: inout TrackDataStore) {
        destination.track = source.track
    }
    
    func navigateToBizInfo(source: UINavigationController, destination: TrackViewController) {
        DispatchQueue.main.async {
            source.pushViewController(destination, animated: true)
        }
    }
    
    //end of class
}
