//
//  TrackViewController.swift
//  SpotifySearch
//
//  Created by Arash Goodarzi on 10/29/19.
//  Copyright (c) 2019 Arash Goodarzi. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TrackDisplayLogic: AnyObject {
    
}

class TrackViewController: UIViewController {
    
    var interactor: TrackBusinessLogic?
    var router: (NSObjectProtocol & TrackRoutingLogic & TrackDataPassing)?
    
    // MARK: Object lifecycle
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }
    
    
    //MARK: Outlets and vars
    
    
    // MARK: Setup
    private func setup() {
        let viewController = self
        let interactor = TrackInteractor()
        let presenter = TrackPresenter()
        let router = TrackRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: View lifecycle
    override func viewDidLoad() {
        super.viewDidLoad()
        
    }
    
    //MARK: Actions
    
    
    //MARK: Funcs
    
    
    //end of class
}

//MARK: - Extensions
extension TrackViewController: TrackDisplayLogic {
    
}
