//
//  TrackModels.swift
//  SpotifySearch
//
//  Created by Arash Goodarzi on 10/29/19.
//  Copyright (c) 2019 Arash Goodarzi. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Track {
    
    enum Set {
        struct Request {
            
        }
        
        struct Response {
            let track: ServerModels.Response.TracksModel.Item?
        }
        
        struct ViewModel {
            let name: String
            let album: String
            let singer: String
            let popularity: String
            let id: String
            let imageUrl: String
        }
    }
}
