//
//  TrackInteractor.swift
//  SpotifySearch
//
//  Created by Arash Goodarzi on 10/29/19.
//  Copyright (c) 2019 Arash Goodarzi. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TrackBusinessLogic: AnyObject {
    func setTrack(request: Track.Set.Request)
}

protocol TrackDataStore {
    var track: ServerModels.Response.TracksModel.Item? { get set }
}

class TrackInteractor: TrackBusinessLogic, TrackDataStore {
    var track: ServerModels.Response.TracksModel.Item? 
    var presenter: TrackPresentationLogic?
    
    func setTrack(request: Track.Set.Request) {
        let response = Track.Set.Response(track: track)
        presenter?.presentSetTrack(response: response)
    }
    
    //end of class
}
