//
//  LoginRouter.swift
//  SpotifySearch
//
//  Created by Arash Goodarzi on 10/29/19.
//  Copyright (c) 2019 Arash Goodarzi. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol LoginRoutingLogic: AnyObject {
    func routeToSearch()
}

protocol LoginDataPassing {
    var dataStore: LoginDataStore? { get }
}

class LoginRouter: NSObject, LoginRoutingLogic, LoginDataPassing {
    
    weak var viewController: LoginViewController?
    var dataStore: LoginDataStore?
    
    func routeToSearch() {
        let destinationVC = SearchViewController.instantiateFrom(storyboard: .main)
        guard var destinationDS = destinationVC.router?.dataStore, let dataStore = self.dataStore, let viewController = viewController else {
            return
        }
        
        passDataToBizInfo(source: dataStore, destination: &destinationDS)
        navigateToBizInfo(source: viewController, destination: destinationVC)
    }
    
    func passDataToBizInfo(source: LoginDataStore, destination: inout SearchDataStore) {
        
    }
    
    func navigateToBizInfo(source: LoginViewController, destination: SearchViewController) {
        DispatchQueue.main.async {
            source.present(destination, animated: true, completion: nil)
        }
        
    }
    //end of class
}
